Keturi/Models/Highscore.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Keturi.Models
{
    public class Highscore
    {
        public int ID { get; set; }
        public string Nickname { get; set; }
        public int Score { get; set; }

        public virtual ApplicationUser User { get; set; }
        
        public string ApplicationUserId { get; set; }
    }
}

Keturi/Controllers/HighscoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Keturi.Models;
using PagedList;

namespace Keturi.Controllers
{
    public class HighscoresController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // Patiekiami visi zaidima uzbaigusiu rezultatai (sorting, paging, filtering)
        // GET: Highscores
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.ScoreSortParm = String.IsNullOrEmpty(sortOrder) ? "score_desc" : "";
            ViewBag.NicknameSortParm = sortOrder == "Nickname" ? "nickname_desc": "Nickname";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var highscores = from s in db.Highscores select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                highscores = highscores.Where(s => s.Nickname.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "nickname_desc":
                    highscores = highscores.OrderByDescending(s => s.Nickname);
                    break;
                case "score_desc":
                    highscores = highscores.OrderByDescending(s => s.Score);
                    break;
                case "Nickname":
                    highscores = highscores.OrderBy(s => s.Nickname);
                    break;
                default:
                    highscores = highscores.OrderBy(s => s.Score);
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(highscores.ToPagedList(pageNumber, pageSize));
        }

        // Administratorius gali keisti irasus

        // GET: Highscores/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Highscore highscore = db.Highscores.Find(id);
            if (highscore == null)
            {
                return HttpNotFound();
            }
            return View(highscore);
        }

        // POST: Highscores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit([Bind(Include = "ID,Nickname,Score,ApplicationUserId")] Highscore highscore)
        {
            if (ModelState.IsValid)
            {
                db.Entry(highscore).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(highscore);
        }

        // Administratorius gali trinti irasus

        // GET: Highscores/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Highscore highscore = db.Highscores.Find(id);
            if (highscore == null)
            {
                return HttpNotFound();
            }
            return View(highscore);
        }

        // POST: Highscores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteConfirmed(int id)
        {
            Highscore highscore = db.Highscores.Find(id);
            db.Highscores.Remove(highscore);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Keturi/Views/Highscores/Create.cshtml
@model Keturi.Models.Highscore

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Highscore</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nickname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nickname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nickname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationUserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Keturi/Views/Highscores/Delete.cshtml
@model Keturi.Models.Highscore

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Highscore</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nickname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nickname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUserId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Keturi/Views/Highscores/Details.cshtml
@model Keturi.Models.Highscore

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Highscore</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nickname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nickname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Score)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Score)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUserId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Keturi/Views/Highscores/Edit.cshtml
@model Keturi.Models.Highscore

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Highscore</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Nickname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nickname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nickname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Score, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Score, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Score, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Keturi/Views/Highscores/Index.cshtml
@model PagedList.IPagedList<Keturi.Models.Highscore>
@using PagedList.Mvc

@{
    ViewBag.Title = "Rezultatai";
}
<br />
@using (Html.BeginForm("Index", "Highscores", FormMethod.Get))
{
    <p>
        Ieškoti pagal niką: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Ieškoti" />
    </p>
}

    <table class="table">
        <tr>
            <th>
                @Html.ActionLink("Nickname", "Index", new { sortOrder = ViewBag.NicknameSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th>
                @Html.ActionLink("Score", "Index", new { sortOrder = ViewBag.ScoreSortParm, currentFilter = ViewBag.CurrentFilter })
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nickname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Score)
                </td>
                <td>
                    @if (this.User.IsInRole("Administrator"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.ID })
                        <br />
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    }
                </td>
            </tr>
        }

    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))